-- MySQL Script generated by MySQL Workbench
-- qua 09 mar 2022 17:37:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DinDinAgora
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DinDinAgora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DinDinAgora` ;
USE `DinDinAgora` ;

-- -----------------------------------------------------
-- Table `DinDinAgora`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DinDinAgora`.`endereco` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(255) NOT NULL,
  `CEP` VARCHAR(255) NOT NULL,
  `complemento` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DinDinAgora`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DinDinAgora`.`cliente` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `RG` VARCHAR(255) NOT NULL,
  `CPF` VARCHAR(255) NOT NULL,
  `enderecoFK` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_cliente_endereco_idx` (`enderecoFK` ASC) VISIBLE,
  UNIQUE INDEX `enderecoFK_UNIQUE` (`enderecoFK` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_endereco`
    FOREIGN KEY (`enderecoFK`)
    REFERENCES `DinDinAgora`.`endereco` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = binary;


-- -----------------------------------------------------
-- Table `DinDinAgora`.`conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DinDinAgora`.`conta` (
  `ID` INT NOT NULL,
  `cliente_fk` INT NOT NULL,
  `saldo` FLOAT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_conta_cliente_idx` (`cliente_fk` ASC) VISIBLE,
  UNIQUE INDEX `cliente_fk_UNIQUE` (`cliente_fk` ASC) VISIBLE,
  CONSTRAINT `fk_conta_cliente`
    FOREIGN KEY (`cliente_fk`)
    REFERENCES `DinDinAgora`.`cliente` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DinDinAgora`.`transferencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DinDinAgora`.`transferencia` (
  `ID` INT NOT NULL,
  `montante` FLOAT NOT NULL,
  `origem_fk` INT NOT NULL,
  `destino_fk` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_transferencia_origem_idx` (`origemFK` ASC) VISIBLE,
  INDEX `fk_transferencia_destino_idx` (`destinoFK` ASC) VISIBLE,
  CONSTRAINT `fk_transferencia_origem`
    FOREIGN KEY (`origemFK`)
    REFERENCES `DinDinAgora`.`conta` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transferencia_destino`
    FOREIGN KEY (`destinoFK`)
    REFERENCES `DinDinAgora`.`conta` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DinDinAgora`.`deposito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DinDinAgora`.`deposito` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `montante` FLOAT NOT NULL,
  `conta_fk` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_deposito_cliente_idx` (`conta_fk` ASC) VISIBLE,
  CONSTRAINT `fk_deposito_conta`
    FOREIGN KEY (`conta_fk`)
    REFERENCES `DinDinAgora`.`conta` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DinDinAgora`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DinDinAgora`.`emprestimo` (
  `ID` INT NOT NULL,
  `montante` FLOAT NOT NULL,
  `conta_fk` INT NOT NULL,
  `parcelas` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_emprestimo_cliente_idx` (`conta_fk` ASC) VISIBLE,
  CONSTRAINT `fk_emprestimo_conta`
    FOREIGN KEY (`conta_fk`)
    REFERENCES `DinDinAgora`.`conta` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;