version: "3.8"
services:
  db:
    build: .
    container_name: dindin_pgdatabase
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      PGPASSWORD: admin
      PGDATA: 'local_pgdata:/var/lib/postgresql/data/pg-data/'
    volumes:
      - 'local_pgdata:/var/lib/postgresql/data/pg-data'
    image: rubauliant/dindin_pgdatabase:1

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: